# -*- coding: utf-8 -*-
"""Worldcloud-g2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ZmOCs7aihsr1afeA9ysIS9u2q80aQH4
"""

# Exercice 1
# author CM
# state: ongoing

# Exercice 2
# author NN
# state: ongoing

# Exercice 3
# author AF
# state: ongoing

